import "@/app/globals.css";

import type { Metadata } from "next";
import { JetBrains_Mono as FontMono } from "next/font/google";
import type { PropsWithChildren } from "react";

import { cn } from "@/lib/utils";

const fontMono = FontMono({ subsets: ["latin"], variable: "--font-mono" });

export const metadata: Metadata = {
  description: "Generated by create next app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
  title: "Create Next App",
};

export default function RootLayout({ children }: Readonly<PropsWithChildren>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={cn(fontMono.variable, "font-mono antialiased")}>{children}</body>
    </html>
  );
}
